### ISSUE TITLE
Zotprime sync under proxy

### ISSUE THREAD

**Issue by aitianshi** [uniuuu/zotprime#12]
Hi @uniuuu !
Thanks for your hardwork for this full on-premise Zotero, I managed to make it work perfectly on a open network.
However I have some trouble when using a proxy. I handle all the backend and frontend (client) installation part but when it's coming to the sync, it cannot connect to the server.

Here is my setup:

1. Machine A has IP `X.X.X.X` and I changed .env the `DSHOST` to its IP --> OK
2. Machine A: installation of backend under proxy `http_proxy` and `https_proxy` --> OK
3. Machine A: compile windows client for machine B and pass parameters `HOST_DS="http://X.X.X.X:8080"` and `HOST_ST="http://X.X.X.X:9000"` --> OK 
4. Machine B is also under proxy and machines A and B are on the **same network** --> OK
5. Transfer the windows client to machine B and open Zotero --> OK
6. Try to sync using credentials admin/admin --> FAIL, cannot connect

Is there a missing step to support it ? I also tried to use the machine A local client with full IPs to `localhost` but it still cannot sync.
Thanks for your time and anyone who is willing to help solve this case !

EDIT: I can access `phpmyadmin` and `minio` through machine A and B.

**Comment by uniuuu** [comment]
Hi @aitianshi 

Thank you for trying this out. 
I am sure it's possible to get it up for your setup.
You mentioned open network and proxy. Where open network means just no proxy I presume.
What kind of proxy you use and what configuration it has?

**Comment by aitianshi** [comment]
Hi @uniuuu

Thanks for the quick feedback.

Open network means in fact no proxy involved. Proxy used is under the pattern `http_proxy=http://127.0.0.1:port` and  `https_proxy=http://127.0.0.1:port`. 
I use it in the `client.Dockerfile` (i.e `RUN export http_proxy=http://127.0.0.1:port` which is working well) to get some resources (like apt/apk update and install, npm/node, etc...). I also tried to unset it at the end of the file but without success. I also have some ca-certificates installed for `curl` usage.

As mentioned, I can access `phpmyadmin` and `minio` using the `IP:port` of the server machine. It seems the dataserver endpoints from client to dataserver or dataserver to another service are not working.

As the only difference between my personal network and proxy network is the proxy, I assume it blocks something (even if it can be strange). I am trying to get the logs of all containers to see if an error appears and which mistake I made.

**Comment by aitianshi** [comment]
Update: when I try to sync, the dataserver gives me the following message:
```php
[php:warn] [pid 30] [client 10..5.5.1:41748] PHP Warning: require(/var/www/zotero/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/zotero/include/header.inc.php on line 142
```
Followed by:
```php
[php:error] [pid 30] [client 10..5.5.1:41748] PHP Fatal error: Uncaught error: Failed opening required '/var/www/zotero/vendor/autoload.php' (include_path='../include') in /var/www/zotero/include/header.inc.php:142\nStack trace:\n#0 {main}\n thrown in  /var/www/zotero/include/header.inc.php on line 142
10.5.5.1 - - [...] "POPST /keys HTTP/1.1" 500 - "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
```

**Comment by aitianshi** [comment]
Update: Dataserver can't use `curl` because of lack of certficate and proxy I believe (same as client.Dockerfile). 
How could I modify the `uniuu/zotprime-dataserver` image to set up that ?

**Comment by uniuuu** [comment]
> Update: Dataserver can't use `curl` because of lack of certficate and proxy I believe (same as client.Dockerfile). How can I access the `uniuu/zotprime-dataserver` image creation so I can set up that ?

You can use` docker save` and `docker load` .
Refer to https://stackoverflow.com/questions/23935141/how-to-copy-docker-images-from-one-host-to-another-without-using-a-repository

**Comment by aitianshi** [comment]
I did think about this trick for the client but I didn't think it would work for the `dataserver`.
The sync is working fine now ! Gonna test all features later.

For those who found the same issue, there is the trick:
- clone zotprime in your closed network (let's say `machine A`) and install everything as the README shows
- clone zotprime in your public network (let's say `machine B`) and install everything as the README shows
- Remove the `uniuu/zotprime-dataserver` container and image from `machine A`
- Import the `uniuu/zotprime-dataserver` image from `machine B` through the following commands
```
# Export from machine B
docker commit DATASERVER_CONTAINER_ID DATASERVER_IMAGE_ID
docker save -o misc.tar DATASERVER_IMAGE_ID
# Import in machine A
docker load -i misc.tar
# Rename if necessary (here my tag used is 2.6.1-rc)
docker tag DATASERVER_NEW_IMAGE_ID uniuu/zotprime-dataserver:2.6.1-rc
```
- Run the whole thing through docker using `docker compose up -d`

And try the sync feature !

For the client, juste export the windows or linux folder from `build` folder and import it to your private network.

Thanks @uniuuu  !
