### ISSUE TITLE
zotero client

### ISSUE THREAD

**Issue by webysther** [uniuuu/zotprime#20]
https://hub.docker.com/r/webysther/zotero

**Comment by uniuuu** [comment]
@webysther It's a game changer. Bravo!
I see it's deprecated in favor of https://docs.linuxserver.io/images/docker-zotero/#supported-architectures

**Comment by webysther** [comment]
> @webysther It's a game changer. Bravo! I see it's deprecated in favor of https://docs.linuxserver.io/images/docker-zotero/#supported-architectures

Yeap, they created! The guys of the project are incredable! I just think in a good way to create a some sort of AIO of all services of zotero only for the server and want to discuss with you, what you think? You make a really organized job here

**Comment by webysther** [comment]
Maybe a AIO like nextcloud AIO docker or one container only for stream-server and dataserver and tinymce-clean-server to reduce the amount of containers.

**Comment by uniuuu** [comment]
Moved AIO topic to discussions under Ideas.

**Comment by uniuuu** [comment]
https://github.com/uniuuu/zotprime/discussions/23
