### ISSUE TITLE
Zotero Client:  Error: HTTP POST http://<HOST_DS>:8080/users/1/items/<ID>/file failed with status code 500:

### ISSUE THREAD

**Issue by MarkOWiesemann** [uniuuu/zotprime#25]
Hi,

I noticed that my syncs to the zotero bucket fails because it is trying to push to the wrong IP.
```
(3)(+0000002): HTTP POST http://10.5.5.1:9000/zotero/

(3)(+0000001): { "Content-Type": "multipart/form-data; boundary=---------------------------884971a3da4cc8b988cb2ef76dca77bd" }

(1)(+0090038): HTTP POST http://10.5.5.1:9000/zotero/ failed with status code 0

(2)(+0000001): Channel status was 2152398862

(2)(+0000001): Channel status was 2152398862

(1)(+0000002): S3 returned 0 (1/GG6LKYHV) -- retrying upload
```

Instead of the docker internal ip "10.5.5.1" it should send it to the IP configured (in my case 10.0.3.101). But it does send to the zotero-fulltext bucket correctly.

I am on origin/development. Do you need any more informations?

**Comment by MarkOWiesemann** [comment]
I made it work by also adjusting the .env file to match:
`S3HOST=10.0.3.101:9000`

Even though I still find this error:

`(1)(+0000004): Error: HTTP POST http://10.0.3.101:8080/users/1/items/MFZ3EFWD/file failed with status code 500: An error occurred Error: HTTP POST http://10.0.3.101:8080/users/1/items/MFZ3EFWD/file failed with status code 500: An error occurred Zotero.HTTP</this.UnexpectedStatusException@chrome://zotero/content/xpcom/http.js:21:18 Zotero.HTTP</this._requestInternal/xmlhttp.onloadend<@chrome://zotero/content/xpcom/http.js:524:25 From previous event: runFunc@resource://zotero/concurrentCaller.js:224:22 ConcurrentCaller.prototype._processNext@resource://zotero/concurrentCaller.js:265:3 ConcurrentCaller.prototype.start@resource://zotero/concurrentCaller.js:156:12 serial/<@chrome://zotero/content/xpcom/utilities_internal.js:1905:14 ZoteroPane</this.sync@chrome://zotero/content/zoteroPane.js:2720:5 oncommand@chrome://zotero/content/standalone/standalone.xul:1:1`

but that might be a different issue. I am investigating

**Comment by MarkOWiesemann** [comment]
Error I found in the dataserver log:
`[Fri May 31 18:13:44.223448 2024] [php:notice] [pid 734] [client 10.0.4.6:48082] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS new\n\t\t\t\tON DUPLICATE KEY UPDATE storageFileID=new.storageFileID, mtime=new...' at line 1\n\nShard: 1\n\nQuery:\nINSERT INTO storageFileItems (storageFileID, itemID, mtime, size) VALUES (?,?,?,?) AS new\n\t\t\t\tON DUPLICATE KEY UPDATE storageFileID=new.storageFileID, mtime=new.mtime, size=new.size\n\nParams:\nArray\n(\n)\n\n\n\n\nShard: 1\n\nQuery:\nINSERT INTO storageFileItems (storageFileID, itemID, mtime, size) VALUES (?,?,?,?) AS new\n\t\t\t\tON DUPLICATE KEY UPDATE storageFileID=new.storageFileID, mtime=new.mtime, size=new.size\n\nParams:\nArray\n(\n    [0] => 33\n    [1] => 2\n    [2] => 1717096042000\n    [3] => 473490\n)\n\n\n in /var/www/zotero/include/DB.inc.php:1303 (POST /users/1/items/MFZ3EFWD/file) (6c9f6600ac)
10.0.4.6 - - [31/May/2024:18:13:44 +0200] "POST /users/1/items/MFZ3EFWD/file HTTP/1.1" 500 17 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
[Fri May 31 18:13:44.309342 2024] [php:warn] [pid 735] [client 10.0.4.6:48096] PHP Warning:  iconv(): Wrong encoding, conversion from &quot;UTF-8&quot; to &quot;ASCII//IGNORE&quot; is not allowed in /var/www/zotero/model/Item.inc.php on line 3159
`

Might be caused by incomplete syncs?

**Comment by MarkOWiesemann** [comment]
This might causes the issue: https://github.com/uniuuu/zotprime/blob/d4c08392d8d49bc89f01e5e7ca85ff3280f47aee/stack/dataserver/config/Storage.inc.php#L568-L569

It looks like postgres syntax but the docker file uses mariadb.

In mariadb it probably should be sth like this:

```
INSERT INTO storageFileItems (storageFileID, itemID, mtime, size)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    storageFileID = VALUES(storageFileID),
    mtime = VALUES(mtime),
    size = VALUES(size);
```

Not tested!

**Comment by MarkOWiesemann** [comment]
Hey that fixed it for me :D, if you wouldn't mind you could apply a patch

**Comment by uniuuu** [comment]
> This might causes the issue:
> 
> https://github.com/uniuuu/zotprime/blob/d4c08392d8d49bc89f01e5e7ca85ff3280f47aee/stack/dataserver/config/Storage.inc.php#L568-L569
> 
> It looks like postgres syntax but the docker file uses mariadb.
> 
> In mariadb it probably should be sth like this:
> 
> ```
> INSERT INTO storageFileItems (storageFileID, itemID, mtime, size)
> VALUES (?, ?, ?, ?)
> ON DUPLICATE KEY UPDATE
>     storageFileID = VALUES(storageFileID),
>     mtime = VALUES(mtime),
>     size = VALUES(size);
> ```
> 
> Not tested!

@MarkOWiesemann Responded on this under pull request.

**Comment by uniuuu** [comment]
> Hi,
> 
> I noticed that my syncs to the zotero bucket fails because it is trying to push to the wrong IP.
> 
> ```
> (3)(+0000002): HTTP POST http://10.5.5.1:9000/zotero/
> 
> (3)(+0000001): { "Content-Type": "multipart/form-data; boundary=---------------------------884971a3da4cc8b988cb2ef76dca77bd" }
> 
> (1)(+0090038): HTTP POST http://10.5.5.1:9000/zotero/ failed with status code 0
> 
> (2)(+0000001): Channel status was 2152398862
> 
> (2)(+0000001): Channel status was 2152398862
> 
> (1)(+0000002): S3 returned 0 (1/GG6LKYHV) -- retrying upload
> ```
> 
> Instead of the docker internal ip "10.5.5.1" it should send it to the IP configured (in my case 10.0.3.101). But it does send to the zotero-fulltext bucket correctly.
> 
> I am on origin/development. Do you need any more informations?

The IP should be correct, you can verify it with command `ip a | grep inet` and see a bridge interface with 10.5.5.1

> I made it work by also adjusting the .env file to match: `S3HOST=10.0.3.101:9000`
> 
> Even though I still find this error:
> 
> `(1)(+0000004): Error: HTTP POST http://10.0.3.101:8080/users/1/items/MFZ3EFWD/file failed with status code 500: An error occurred Error: HTTP POST http://10.0.3.101:8080/users/1/items/MFZ3EFWD/file failed with status code 500: An error occurred Zotero.HTTP</this.UnexpectedStatusException@chrome://zotero/content/xpcom/http.js:21:18 Zotero.HTTP</this._requestInternal/xmlhttp.onloadend<@chrome://zotero/content/xpcom/http.js:524:25 From previous event: runFunc@resource://zotero/concurrentCaller.js:224:22 ConcurrentCaller.prototype._processNext@resource://zotero/concurrentCaller.js:265:3 ConcurrentCaller.prototype.start@resource://zotero/concurrentCaller.js:156:12 serial/<@chrome://zotero/content/xpcom/utilities_internal.js:1905:14 ZoteroPane</this.sync@chrome://zotero/content/zoteroPane.js:2720:5 oncommand@chrome://zotero/content/standalone/standalone.xul:1:1`
> 
> but that might be a different issue. I am investigating

Here you confirmed that IP was correct and that changing it hasn't resolved issue.

**Comment by uniuuu** [comment]
Changed subject to align with the issue.

**Comment by uniuuu** [comment]
Yes I confirm the `HTTP POST http://127.0.0.1:8080/users/1/items/YNMKXLU4/file failed with status code 500:` 
is due to server error `[php:notice] [pid 735:tid 735] [client 10.5.5.1:57874] 
You have an error in your SQL syntax; check the manual that corresponds to 
your MariaDB server version for the right syntax to use near
 'AS new\n\t\t\t\tON DUPLICATE KEY UPDATE storageFileID=new.storageFileID, mtime=new...' 
 at line 1\n\nShard: 1\n\nQuery:\nINSERT INTO storageFileItems (storageFileID, itemID, mtime, size) 
 VALUES (?,?,?,?) AS new\n\t\t\t\tON DUPLICATE KEY UPDATE storageFileID=new.storageFileID,
  mtime=new.mtime, size=new.size\n\nParams:\nArray\n(\n)\n\n\n\n\nShard: 1\n\nQuery:\nINSERT 
  INTO storageFileItems (storageFileID, itemID, mtime, size) VALUES (?,?,?,?) AS new\n\t\t\t\tON 
  DUPLICATE KEY UPDATE storageFileID=new.storageFileID, mtime=new.mtime, 
  size=new.size\n\nParams:\nArray\n(\n    [0] => 3\n    [1] => 1\n    [2] => 1727458996913\n 
     [3] => 792201\n)\n\n\n in /var/www/zotero/include/DB.inc.php:1303 
     (POST /users/1/items/6SQQNQS7/file) (bb6f74ab5b)`
   

> > This might causes the issue:
> > https://github.com/uniuuu/zotprime/blob/d4c08392d8d49bc89f01e5e7ca85ff3280f47aee/stack/dataserver/config/Storage.inc.php#L568-L569
> > 
> > It looks like postgres syntax but the docker file uses mariadb.
> > In mariadb it probably should be sth like this:
> > ```
> > INSERT INTO storageFileItems (storageFileID, itemID, mtime, size)
> > VALUES (?, ?, ?, ?)
> > ON DUPLICATE KEY UPDATE
> >     storageFileID = VALUES(storageFileID),
> >     mtime = VALUES(mtime),
> >     size = VALUES(size);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not tested!
> 
> @MarkOWiesemann Responded on this under pull request.

PR fixes it https://github.com/uniuuu/zotprime/pull/26
