### ISSUE TITLE
Sync Issues

### ISSUE THREAD

**Issue by MarkOWiesemann** [uniuuu/zotprime#36]
I am trying to understand the issues from syncing but I am having some problems:
Zotero Client v7 Error log:
```
18:16:38.862 1728231398862	addons.xpi	WARN	Not converting unknown addon type undefined
18:16:38.911
NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsICommandLine.handleFlagWithParam] [BrowserContentHandler.sys.mjs:428](resource:///modules/BrowserContentHandler.sys.mjs)
18:16:38.916
NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsICommandLine.handleFlagWithParam]
    dch_handle resource:///modules/BrowserContentHandler.sys.mjs:1289
[BrowserContentHandler.sys.mjs:1308:15](resource:///modules/BrowserContentHandler.sys.mjs)
18:16:38.917
Warning: unrecognized command line flag -url
[BrowserContentHandler.sys.mjs:1344:17](resource:///modules/BrowserContentHandler.sys.mjs)
18:16:39.216 Error: Cannot find loader for bootstrap [XPIProvider.jsm:1935:15](resource://gre/modules/addons/XPIProvider.jsm)
18:16:39.302 unreachable code after return statement
[util.js:205:4](resource://zotero/bluebird/util.js)
18:16:39.811 Missing resource in locale en-AU: branding/brand.ftl
18:16:39.811 Missing resource in locale en-CA: branding/brand.ftl
18:16:39.812 Missing resource in locale en-NZ: branding/brand.ftl
18:16:40.085 Missing resource in locale en-AU: browser/browserSets.ftl
18:16:40.086 Missing resource in locale en-CA: browser/browserSets.ftl
18:16:40.095 Missing resource in locale en-NZ: browser/browserSets.ftl
18:16:45.840 HTTP GET http://10.0.3.32:8080/retractions/list failed with status code 404:

<h1>Not Found</h1>
<p>The page you requested could not be found.</p>
3
18:16:52.793 Missing resource in locale en-AU: devtools/client/toolbox.ftl
18:16:52.794 Missing resource in locale en-CA: devtools/client/toolbox.ftl
18:16:52.795 Missing resource in locale en-NZ: devtools/client/toolbox.ftl
18:17:35.896
DOMException: Could not get children of file(/home/mark/.zotero/zotero/Crash Reports/events) because it does not exist [CrashManager.sys.mjs:663:17](resource://gre/modules/CrashManager.sys.mjs)
18:18:12.621 S3 returned 0 (1/2BDXE32R) -- retrying upload
18:18:12.624 S3 returned 0 (1/23YVQ2VE) -- retrying upload
18:19:44.657 S3 returned 0 (1/2BDXE32R) -- retrying upload
18:19:46.656 S3 returned 0 (1/23YVQ2VE) -- retrying upload
18:21:22.688 S3 returned 0 (1/2BDXE32R) -- retrying upload
18:21:32.691 Upload request 1/23YVQ2VE failed
18:21:32.693 A file sync error occurred. Please restart Zotero and/or your computer and try syncing again.

If the error persists, there may be a problem with either your computer or your network: security software, proxy server, VPN, etc. Try disabling any security/firewall software you're using or, if this is a laptop, try from a different network. [zfs.js:699](chrome://zotero/content/xpcom/storage/zfs.js)
18:23:02.863 S3 returned 0 (1/35HS8U9U) -- retrying upload
18:23:24.869 S3 returned 0 (1/2BDXE32R) -- retrying upload
```

Minio is empty but reachble. Buckets exist though. Also can't find any hints in the dataserver log:
```
10.0.4.10 - - [06/Oct/2024:18:16:40 +0200] "GET /keys/current HTTP/1.1" 200 178 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.0.4.10 - - [06/Oct/2024:18:16:40 +0200] "GET /users/1/groups?format=versions HTTP/1.1" 200 14 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.5.5.10 - - [06/Oct/2024:18:16:40 +0200] "GET /keys/current?showid=1 HTTP/1.1" 200 408 "-" "-"
10.5.5.10 - - [06/Oct/2024:18:16:40 +0200] "GET /users/1/groups HTTP/1.1" 200 862 "-" "-"
10.0.4.10 - - [06/Oct/2024:18:16:41 +0200] "GET /users/1/settings?since=38 HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.0.4.10 - - [06/Oct/2024:18:16:41 +0200] "GET /groups/1/settings HTTP/1.1" 200 2 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.0.4.10 - - [06/Oct/2024:18:16:41 +0200] "GET /groups/1/collections?format=versions HTTP/1.1" 200 2 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.0.4.10 - - [06/Oct/2024:18:16:41 +0200] "GET /groups/1/searches?format=versions HTTP/1.1" 200 2 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.0.4.10 - - [06/Oct/2024:18:16:41 +0200] "GET /groups/1/items/top?format=versions&includeTrashed=1 HTTP/1.1" 200 2 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.0.4.10 - - [06/Oct/2024:18:16:41 +0200] "GET /groups/1/items?format=versions&includeTrashed=1 HTTP/1.1" 200 2 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.0.4.10 - - [06/Oct/2024:18:16:41 +0200] "GET /groups/1/deleted?since=0 HTTP/1.1" 200 72 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.0.4.10 - - [06/Oct/2024:18:16:41 +0200] "POST /users/1/items/2BDXE32R/file HTTP/1.1" 200 871 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.0.4.10 - - [06/Oct/2024:18:16:41 +0200] "POST /users/1/items/23YVQ2VE/file HTTP/1.1" 200 870 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.0.4.10 - - [06/Oct/2024:18:16:45 +0200] "GET /retractions/list HTTP/1.1" 404 84 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.0.4.10 - - [06/Oct/2024:18:16:46 +0200] "GET /retractions/list HTTP/1.1" 404 84 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.0.4.10 - - [06/Oct/2024:18:21:32 +0200] "POST /users/1/items/35HS8U9U/file HTTP/1.1" 200 869 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
```
I am currently using the production branch but could switch to development for debugging purpose.

@uniuuu do you have any ideas? I would prefer to fix this issue before looking into the groups

**Comment by uniuuu** [comment]
Hi @MarkOWiesemann 

I need to reproduce it. If you can provide step by step description including server and client installation part to get these errors then.
- addon warning
- warning unrecognized command line flag -url
- Error: Cannot find loader for bootstrap [XPIProvider.jsm:1935:15](resource://gre/modules/addons/XPIProvider.jsm). unreachable code after return statement
- DOMException: Could not get children of file

Please run also `docker compose logs -f` to see what errors are on server side when the below quoted are thrown by client.


> I am trying to understand the issues from syncing but I am having some problems: Zotero Client v7 Error log:
> 
> ```
> 18:16:38.862 1728231398862	addons.xpi	WARN	Not converting unknown addon type undefined
> 18:16:38.911
> NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsICommandLine.handleFlagWithParam] [BrowserContentHandler.sys.mjs:428](resource:///modules/BrowserContentHandler.sys.mjs)
> 18:16:38.916
> NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsICommandLine.handleFlagWithParam]
>     dch_handle resource:///modules/BrowserContentHandler.sys.mjs:1289
> [BrowserContentHandler.sys.mjs:1308:15](resource:///modules/BrowserContentHandler.sys.mjs)
> 18:16:38.917
> Warning: unrecognized command line flag -url
> [BrowserContentHandler.sys.mjs:1344:17](resource:///modules/BrowserContentHandler.sys.mjs)
> 18:16:39.216 Error: Cannot find loader for bootstrap [XPIProvider.jsm:1935:15](resource://gre/modules/addons/XPIProvider.jsm)
> 18:16:39.302 unreachable code after return statement
> [util.js:205:4](resource://zotero/bluebird/util.js)
> 18:16:39.811 Missing resource in locale en-AU: branding/brand.ftl
> 18:16:39.811 Missing resource in locale en-CA: branding/brand.ftl
> 18:16:39.812 Missing resource in locale en-NZ: branding/brand.ftl
> 18:16:40.085 Missing resource in locale en-AU: browser/browserSets.ftl
> 18:16:40.086 Missing resource in locale en-CA: browser/browserSets.ftl
> 18:16:40.095 Missing resource in locale en-NZ: browser/browserSets.ftl
> 18:16:45.840 HTTP GET http://10.0.3.32:8080/retractions/list failed with status code 404:
> 
> <h1>Not Found</h1>
> <p>The page you requested could not be found.</p>
> 3
> 18:16:52.793 Missing resource in locale en-AU: devtools/client/toolbox.ftl
> 18:16:52.794 Missing resource in locale en-CA: devtools/client/toolbox.ftl
> 18:16:52.795 Missing resource in locale en-NZ: devtools/client/toolbox.ftl
> 18:17:35.896
> DOMException: Could not get children of file(/home/mark/.zotero/zotero/Crash Reports/events) because it does not exist [CrashManager.sys.mjs:663:17](resource://gre/modules/CrashManager.sys.mjs)
> 18:18:12.621 S3 returned 0 (1/2BDXE32R) -- retrying upload
> 18:18:12.624 S3 returned 0 (1/23YVQ2VE) -- retrying upload
> 18:19:44.657 S3 returned 0 (1/2BDXE32R) -- retrying upload
> 18:19:46.656 S3 returned 0 (1/23YVQ2VE) -- retrying upload
> 18:21:22.688 S3 returned 0 (1/2BDXE32R) -- retrying upload
> 18:21:32.691 Upload request 1/23YVQ2VE failed
> 18:21:32.693 A file sync error occurred. Please restart Zotero and/or your computer and try syncing again.
> 
> If the error persists, there may be a problem with either your computer or your network: security software, proxy server, VPN, etc. Try disabling any security/firewall software you're using or, if this is a laptop, try from a different network. [zfs.js:699](chrome://zotero/content/xpcom/storage/zfs.js)
> 18:23:02.863 S3 returned 0 (1/35HS8U9U) -- retrying upload
> 18:23:24.869 S3 returned 0 (1/2BDXE32R) -- retrying upload
> ```
> 
> Minio is empty but reachble. Buckets exist though. Also can't find any hints in the dataserver log:
> 
> ```
> 10.0.4.10 - - [06/Oct/2024:18:16:40 +0200] "GET /keys/current HTTP/1.1" 200 178 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
> 10.0.4.10 - - [06/Oct/2024:18:16:40 +0200] "GET /users/1/groups?format=versions HTTP/1.1" 200 14 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
> 10.5.5.10 - - [06/Oct/2024:18:16:40 +0200] "GET /keys/current?showid=1 HTTP/1.1" 200 408 "-" "-"
> 10.5.5.10 - - [06/Oct/2024:18:16:40 +0200] "GET /users/1/groups HTTP/1.1" 200 862 "-" "-"
> 10.0.4.10 - - [06/Oct/2024:18:16:41 +0200] "GET /users/1/settings?since=38 HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
> 10.0.4.10 - - [06/Oct/2024:18:16:41 +0200] "GET /groups/1/settings HTTP/1.1" 200 2 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
> 10.0.4.10 - - [06/Oct/2024:18:16:41 +0200] "GET /groups/1/collections?format=versions HTTP/1.1" 200 2 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
> 10.0.4.10 - - [06/Oct/2024:18:16:41 +0200] "GET /groups/1/searches?format=versions HTTP/1.1" 200 2 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
> 10.0.4.10 - - [06/Oct/2024:18:16:41 +0200] "GET /groups/1/items/top?format=versions&includeTrashed=1 HTTP/1.1" 200 2 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
> 10.0.4.10 - - [06/Oct/2024:18:16:41 +0200] "GET /groups/1/items?format=versions&includeTrashed=1 HTTP/1.1" 200 2 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
> 10.0.4.10 - - [06/Oct/2024:18:16:41 +0200] "GET /groups/1/deleted?since=0 HTTP/1.1" 200 72 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
> 10.0.4.10 - - [06/Oct/2024:18:16:41 +0200] "POST /users/1/items/2BDXE32R/file HTTP/1.1" 200 871 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
> 10.0.4.10 - - [06/Oct/2024:18:16:41 +0200] "POST /users/1/items/23YVQ2VE/file HTTP/1.1" 200 870 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
> 10.0.4.10 - - [06/Oct/2024:18:16:45 +0200] "GET /retractions/list HTTP/1.1" 404 84 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
> 10.0.4.10 - - [06/Oct/2024:18:16:46 +0200] "GET /retractions/list HTTP/1.1" 404 84 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
> 10.0.4.10 - - [06/Oct/2024:18:21:32 +0200] "POST /users/1/items/35HS8U9U/file HTTP/1.1" 200 869 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
> ```
> 
> I am currently using the production branch but could switch to development for debugging purpose.
> 
> @uniuuu do you have any ideas? I would prefer to fix this issue before looking into the groups

**Comment by uniuuu** [comment]
Hi @MarkOWiesemann 
Please try again to build client with latest code https://github.com/uniuuu/zotprime/releases/tag/v2.8.2.

**Comment by MarkOWiesemann** [comment]
I rebuild the client, also redeployed the dataserver with the docker compose of that tag. But during init.sh I get this error in the dataserver log:
```
PHP Warning:  require(header.inc.php): Failed to open stream: No such file or directory in /var/www/zotero/admin/schema_update on line 4
PHP Fatal error:  Uncaught Error: Failed opening required 'header.inc.php' (include_path='../include') in /var/www/zotero/admin/schema_update:4
Stack trace:
#0 {main}
  thrown in /var/www/zotero/admin/schema_update on line 4
```

This stops the preprints from syncing which is why I can not yet verify if it all works again.

**Comment by uniuuu** [comment]
> I rebuild the client, also redeployed the dataserver with the docker compose of that tag. But during init.sh I get this error in the dataserver log:
> 
> ```
> PHP Warning:  require(header.inc.php): Failed to open stream: No such file or directory in /var/www/zotero/admin/schema_update on line 4
> PHP Fatal error:  Uncaught Error: Failed opening required 'header.inc.php' (include_path='../include') in /var/www/zotero/admin/schema_update:4
> Stack trace:
> #0 {main}
>   thrown in /var/www/zotero/admin/schema_update on line 4
> ```
> 
> This stops the preprints from syncing which is why I can not yet verify if it all works again.

Hi @MarkOWiesemann 
This error usually means that submodules were not updated in repository.
Please try `docker compose down -v` to remove volumes and remove your local repository. Then clone production branch again and try to recreate server.

**Comment by uniuuu** [comment]
Hi @MarkOWiesemann 
The issue: 
> 18:18:12.624 S3 returned 0 (1/23YVQ2VE) -- retrying upload

Has been fixed in https://github.com/uniuuu/zotprime/releases/tag/v2.8.3
