### ISSUE TITLE
Client build error

### ISSUE THREAD

**Issue by Amniotic3** [uniuuu/zotprime#39]
Here's my build command, with the error message

```bash
sudo DOCKER_BUILDKIT=1 docker build --progress=plain --file client.Dockerfile \
      --build-arg HOST_DS=http://192.168.1.161:8080/ \
      --build-arg HOST_ST=ws://192.168.1.161:8081/ \
      --build-arg MLW=w \
      --build-arg HTTP_PROXY=http://192.168.1.8:10809 \
      --build-arg HTTPS_PROXY=http://192.168.1.8:10809 \
      --build-arg ALL_PROXY=http://192.168.1.8:10809 \
      --output build .
```

```bash
#26 12.72 Everything is Ok
#26 12.72
#26 12.72 Archives with Warnings: 1
#26 12.72
#26 12.72 Warnings: 1
#26 12.72 Folders: 9
#26 12.72 Files: 87
#26 12.72 Size:       218006509
#26 12.72 Compressed: 57040328
#26 12.73 /usr/src/app/client/zotero-client/app/xulrunner/firefox-win32 /usr/src/app/client/zotero-client/app/xulrunner
#26 13.41 strings: unrecognized option: e
#26 13.42 BusyBox v1.36.1 (2024-06-10 07:11:47 UTC) multi-call binary.
#26 13.42
#26 13.42 Usage: strings [-fo] [-t o|d|x] [-n LEN] [FILE]...
#26 13.42
#26 13.42 Display printable strings in a binary file
#26 13.42
#26 13.42 	-f		Precede strings with filenames
#26 13.42 	-o		Precede strings with octal offsets
#26 13.42 	-t o|d|x	Precede strings with offsets in base 8/10/16
#26 13.42 	-n LEN		At least LEN characters form a string (default 4)
#26 13.42 "Zotero" not found in xul.dll after replacement
#26 ERROR: process "/bin/sh -c set -eux;      app/scripts/dir_build -p $MLW" did not complete successfully: exit code: 1
------
 > [stage-2 10/10] RUN set -eux;      app/scripts/dir_build -p w:
13.42
13.42 Usage: strings [-fo] [-t o|d|x] [-n LEN] [FILE]...
13.42
13.42 Display printable strings in a binary file
13.42
13.42 	-f		Precede strings with filenames
13.42 	-o		Precede strings with octal offsets
13.42 	-t o|d|x	Precede strings with offsets in base 8/10/16
13.42 	-n LEN		At least LEN characters form a string (default 4)
13.42 "Zotero" not found in xul.dll after replacement
------
client.Dockerfile:77
--------------------
  76 |
  77 | >>> RUN set -eux; \
  78 | >>>      app/scripts/dir_build -p $MLW
  79 |
--------------------
ERROR: failed to solve: process "/bin/sh -c set -eux;      app/scripts/dir_build -p $MLW" did not complete successfully: exit code: 1
```

gpt prompts to modify the client.Dockerfile by adding the following command

```dockerfile
RUN apk add --no-cache binutils
```
The client builds successfully after execution.

However, the client can synchronize the information of the entries, but not the files under the same entry. The error console of the self-built zotero client prompts the following:

This is the error message after clicking the synchronize button after adding a file:

HTTP GET http://192.168.1.161:8080/retractions/list failed with status code 404.

<h1>Not Found</h1
<p>The page you requested could not be found.

S3 returned 0 (1/XB7EJ7XC) -- retrying upload

There are no uploaded files in S3.

This is the error report for the Sync button:

[JavaScript Error: "HTTP GET http://192.168.1.161:8080/retractions/list failed with status code 404:

<h1>Not Found</h1>
<p>The page you requested could not be found.</p>
"]

[JavaScript Error: "未找到匹配的参考文献"]

[JavaScript Error: "S3 returned 0 (1/XB7EJ7XC) -- retrying upload"]

[JavaScript Error: "S3 returned 0 (1/XB7EJ7XC) -- retrying upload"]

[JavaScript Error: "S3 returned 0 (1/XB7EJ7XC) -- retrying upload"]

[JavaScript Error: "S3 returned 0 (1/XB7EJ7XC) -- retrying upload"]

[JavaScript Error: "S3 returned 0 (1/XB7EJ7XC) -- retrying upload"]

[JavaScript Error: "Upload request 1/XB7EJ7XC failed"]

[JavaScript Error: "文件同步发生错误。请重启 Zotero 和/或电脑，然后尝试重新同步。

如果此错误持续存在，你的电脑或网络可能有问题：如安全软件，代理服务器，或者 VPN。请尝试禁用你当前使用的任何安全/防火墙软件；如果你正在使用的是笔记本电脑，请尝试其他网络连接。" {file: "chrome://zotero/content/xpcom/storage/zfs.js" line: 699}]

[JavaScript Error: "S3 returned 0 (1/XB7EJ7XC) -- retrying upload"]

[JavaScript Error: "S3 returned 0 (1/XB7EJ7XC) -- retrying upload"]

[JavaScript Error: "S3 returned 0 (1/XB7EJ7XC) -- retrying upload"]

[JavaScript Error: "Error: Failed to load resource://gre/modules/PlacesDBUtils.sys.mjs"]

[JavaScript Error: "S3 returned 0 (1/XB7EJ7XC) -- retrying upload"]

[JavaScript Error: "S3 returned 0 (1/XB7EJ7XC) -- retrying upload"]

[JavaScript Error: "Upload request 1/XB7EJ7XC failed"]

[JavaScript Error: "文件同步发生错误。请重启 Zotero 和/或电脑，然后尝试重新同步。

如果此错误持续存在，你的电脑或网络可能有问题：如安全软件，代理服务器，或者 VPN。请尝试禁用你当前使用的任何安全/防火墙软件；如果你正在使用的是笔记本电脑，请尝试其他网络连接。" {file: "chrome://zotero/content/xpcom/storage/zfs.js" line: 699}]

appName => Zotero, version => 7.0.7.SOURCE.304e76685 (x64), os => Windows 10.0 17763, locale => zh-CN, extensions => 

> Looking forward to your reply, love from China.

**Comment by Amniotic3** [comment]
I probably solved the problem.

First of all I am using a virtual machine on my side.

To fix the synchronization error, just change S3HOST in the .env file to the IP of the VM.

**Comment by uniuuu** [comment]
Hi @Amniotic3 
Thank you for fix submitted.
> [JavaScript Error: "S3 returned 0 (1/XB7EJ7XC) -- retrying upload"]
To comment on issue: PHP has to set IP address that's accessible from client in order client to be able to access it.
